/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        TempConverter classUnderTest = new TempConverter();

        classUnderTest.setTipo("C");
        classUnderTest.setTemperatura(100);

        assertNotNull(classUnderTest.getTipo(), "app should have a greeting");
    }

    @Test
    void Equals() {
        TempConverter classUnderTest = new TempConverter();

        classUnderTest.setTipo("C");
        classUnderTest.setTemperatura(100);
        assertEquals("C", classUnderTest.getTipo());
    }

    @Test
    void calcularCelsius() {
        TempConverter classUnderTest = new TempConverter();

        classUnderTest.setTipo("C");
        classUnderTest.setTemperatura(100);

        assertNotNull(classUnderTest.getTipo(), "app should have a greeting");
        //assertNot(37.77777777777778, classUnderTest.calcular());
    }
}
