pipeline {
	agent any
    stages {
    	stage('Olá') {
        	steps {
            	sh 'echo Olá Mundo!'
            }
        }
        
        stage('Tchau'){
        	steps {
            	sh 'echo Tchau Mundo!'
            }
        }
    }
}
